spring.application.name=backends
spring.datasource.url=jdbc:mysql://localhost:3306/lms
spring.datasource.username=root
spring.datasource.password=hzkk4567@A

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true